### PR TITLE
[INFRA-312]: add link to epic in Slack notification

### PR DESCRIPTION
**Pull request by kotchaosu**

### CODE REVIEW

**Comment by 23doors** [comment]
what's that for?

**Comment by kotchaosu** [comment]
@lifcio 's request

**Comment by 23doors** [comment]
Sure but `add epics` doesn't really describe what this change does...

**Comment by 23doors** [comment]
Ok, looked up ticket and code so I know that this is only for slack release notification. But some description or meaningful title would be nice :P

**Pull request merged**
